---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/auth/login":
    post:
      summary: Login user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    message: Logged in successfully.
                    token: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxYjhjZmQ0Ny05MGYzLTQzNmUtOTE3OC02ZmI2MDdiMzQ1ZGMiLCJzdWIiOiI1OThmY2Y5NC1kMDcyLTQxNjgtODYyZS0xNjEyODMyYTExZDkiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE3NDY3NTUyNzgsImV4cCI6MTc0Njg0MTY3OH0.3XOhPzcnk3vaXvLiWvfSx-XkR3SNkYRAVOBWKK8pMcE
                    refresh_token:
                      value: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1OThmY2Y5NC1kMDcyLTQxNjgtODYyZS0xNjEyODMyYTExZDkiLCJqdGkiOiIxYjhjZmQ0Ny05MGYzLTQzNmUtOTE3OC02ZmI2MDdiMzQ1ZGMifQ.zRhGigV14k34u9itoq3TgQ0wipfeTcTtgacG9HoopZs
                      httponly: true
                      expires: '2025-05-10T01:47:58.759Z'
                      secure: false
                    user:
                      id: 598fcf94-d072-4168-862e-1612832a11d9
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      email: test@test
                      full_name: German Rodriguez
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/auth/requests/login"
  "/api/auth/signup":
    post:
      summary: Sign up user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    message: Signed up successfully.
                    token: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJmNDE4MTMwYi0wN2Q1LTQyZTgtYmM1NS03NjVjM2Y5OTQ0YTIiLCJzdWIiOiIxNzE4ZDE0Zi05NGJlLTQ5Y2MtYmFjZS00NzY4ODQyODE5ZjIiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE3NDY3NTUyNzgsImV4cCI6MTc0Njg0MTY3OH0.WKdlY9WYzKoJY8qsbz7OFQGaw2zG9cnaEdJ_ao0Ruk0
                    user:
                      id: 1718d14f-94be-49cc-bace-4768842819f2
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      email: teste@teste
                      full_name: 
                    refresh_token:
                      value: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNzE4ZDE0Zi05NGJlLTQ5Y2MtYmFjZS00NzY4ODQyODE5ZjIiLCJqdGkiOiJmNDE4MTMwYi0wN2Q1LTQyZTgtYmM1NS03NjVjM2Y5OTQ0YTIifQ.BJhIAlxe44ajNcrmT7eMTutDsa1YgBLB0Q61pa_jmZY
                      httponly: true
                      expires: '2025-05-10T01:47:58.802Z'
                      secure: false
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/auth/requests/signup"
  "/api/auth/logout":
    delete:
      summary: Logout User
      tags:
      - Auth
      security:
      - bearer_auth: []
      responses:
        '200':
          description: Successful
  "/api/v1/mentor/expertise_areas":
    get:
      summary: List Mentor Expertise Areas
      tags:
      - Mentor Expertise Areas
      security:
      - bearer_auth: []
      parameters:
      - name: search
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Successful with search
          content:
            application/json:
              examples:
                Default:
                  value:
                    meta:
                      current_page: 1
                      total_pages: 1
                      current_page_size: 50
                      total: 1
                    data:
                    - id: f6d5a6b9-92f6-459f-b2b5-5dc178b19a48
                      name: dummy
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
  "/api/v1/mentor/profiles/{id}":
    get:
      summary: Show Mentor Profile
      tags:
      - Mentor Profiles
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: 3de3b57c-af54-4f88-b381-49b8fcfa7fb7
                      availabilities: []
                      bio: Quo nihil omnis. Ad ipsam beatae. Assumenda est qui.
                      client_profiles: []
                      expertise_areas: []
                      headline: Farming Agent
                      hourly_rate: '64.12'
                      linkedin_url: http://linkedin.com/tuan_mueller
                      profile_name: 
                      rating: 6.76
                      sessions: []
                      years_of_experience: 20
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      base:
                      - Couldn't find Mentor::Profile with 'id'=not_an_id
                    request_id: b4750b22-01ca-48cc-ae90-cd64d587bd8d
    put:
      summary: Update Mentor Profile
      tags:
      - Mentor Profiles
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: 41ee4319-0214-42f4-819c-51ac5386f511
                      availabilities: []
                      bio: Updated Bio
                      client_profiles: []
                      expertise_areas: []
                      headline: Updated Headline
                      hourly_rate: '50.0'
                      linkedin_url: https://linkedin.com/in/updated
                      profile_name: Updated Profile
                      rating: 4.5
                      sessions: []
                      years_of_experience: 5
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/mentor/profile/requests/update"
  "/api/v1/users/{id}":
    get:
      summary: Show User
      tags:
      - Users
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: 444bbd16-60d6-4611-a719-94511fff22ee
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      cpf: '09874384417'
                      email: marylouise_langworth@weber.test
                      full_name: Eleni Kreiger
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      base:
                      - Couldn't find User with 'id'=not_an_id
                    request_id: abcb799b-3928-4c1f-ae9d-d037c7bfd425
    put:
      summary: Update User
      tags:
      - Users
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: 2713f41d-f830-4d32-b43c-850f31af7c12
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      cpf: '12496062095'
                      email: admin@acme.com
                      full_name: Dummy Name
        '422':
          description: Unprocessable entity
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      email:
                      - is invalid
                    request_id: 2afb4ec1-41ef-4d11-8e2a-a8f6d7bd7b8a
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      base:
                      - Couldn't find User with 'id'=not_an_id
                    request_id: fb61c52c-559d-485a-a9fb-31e5afd9c3c2
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/users/requests/update"
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
  schemas:
    auth:
      requests:
        login:
          title: User Login Request
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                  example: t@t.com
                password:
                  type: string
                  example: '123456'
              required:
              - email
              - password
          required:
          - user
        signup:
          title: Create User Request
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                  example: test@test
                password:
                  type: string
                full_name:
                  type: string
              required:
              - email
              - password
      responses:
        login:
          title: Create User Response
          type: object
          properties:
            message:
              type: string
            token:
              type: string
            refresh_token:
              type: object
              properties:
                value:
                  type: string
                httponly:
                  type: boolean
                expires:
                  type: string
                secure:
                  type: boolean
            user:
              "$ref": "#/components/schemas/v1/users/_common"
        signup:
          title: Create User Response
          type: object
          properties:
            message:
              type: string
            token:
              type: string
            refresh_token:
              type: object
              properties:
                value:
                  type: string
                httponly:
                  type: boolean
                expires:
                  type: string
                secure:
                  type: boolean
    common:
      pagination_meta:
        title: Pagination Meta
        type: object
        properties:
          current_page:
            type: integer
          total_pages:
            type: integer
          current_page_size:
            type: integer
          total:
            type: integer
        required:
        - current_page
        - total_pages
        - current_page_size
        - total
    v1:
      mentor:
        availabilities:
          _common:
            title: Mentor Availability
            type: object
            additionalProperties: true
            properties:
              id:
                type: string
              start_time:
                type: string
                format: date-time
              end_time:
                type: string
                format: date-time
          _private:
            title: Mentor Availability Private
            type: object
            additionalProperties: true
            properties:
              id:
                type: string
              start_time:
                type: string
                format: date-time
              end_time:
                type: string
                format: date-time
        expertise_areas:
          _common:
            title: Mentor ExpertiseArea
            type: object
            additionalProperties: true
            properties:
              id:
                type: string
              name:
                type: string
          responses:
            index:
              title: Mentor Expertise Areas Response
              type: object
              properties:
                data:
                  type: array
                  items:
                    "$ref": "#/components/schemas/v1/mentor/expertise_areas/_common"
                meta:
                  "$ref": "#/components/schemas/common/pagination_meta"
              required:
              - meta
              - data
        profiles:
          _common:
            title: Mentor Profile
            type: object
            additionalProperties: true
            properties:
              id:
                type: string
              bio:
                type: string
              headline:
                type: string
                nullable: true
              hourly_rate:
                type: string
                nullable: true
              linkedin_url:
                type: string
                nullable: true
              profile_name:
                type: string
                nullable: true
              rating:
                type: number
                format: float
                nullable: true
              years_of_experience:
                type: integer
                nullable: true
              expertise_areas:
                type: array
                items:
                  "$ref": "#/components/schemas/v1/mentor/expertise_areas/_common"
              availabilities:
                type: array
                items:
                  "$ref": "#/components/schemas/v1/mentor/availabilities/_common"
          _private:
            title: Mentor Profile Private
            type: object
            additionalProperties: true
            allOf:
            - "$ref": "#/components/schemas/v1/mentor/profiles/_common"
            properties:
              sessions:
                type: array
                items:
                  "$ref": "#/components/schemas/v1/mentor/session/_common"
              client_profiles:
                type: array
                items:
                  "$ref": "#/components/schemas/v1/mentor/profiles/_common"
          requests:
            update:
              title: Update Mentor Profile Request
              type: object
              properties:
                mentor_profile:
                  type: object
                  properties:
                    bio:
                      type: string
                      nullable: true
                    headline:
                      type: string
                      nullable: true
                    hourly_rate:
                      type: string
                      nullable: true
                    linkedin_url:
                      type: string
                      nullable: true
                    profile_name:
                      type: string
                      nullable: true
                    rating:
                      type: number
                      nullable: true
                    years_of_experience:
                      type: string
                      nullable: true
                  required:
                  - mentor_profile
          responses:
            show:
              title: Show Mentor Profile Response
              type: object
              properties:
                data:
                  "$ref": "#/components/schemas/v1/mentor/profiles/_private"
              required:
              - data
            update:
              title: Update Mentor Profile Response
              type: object
              properties:
                data:
                  "$ref": "#/components/schemas/v1/mentor/profiles/_private"
              required:
              - data
      users:
        _common:
          title: User
          type: object
          additionalProperties: true
          properties:
            id:
              type: string
            full_name:
              type: string
              nullable: true
            email:
              type: string
              nullable: true
        _private:
          title: User Private
          type: object
          additionalProperties: true
          properties:
            id:
              type: string
            full_name:
              type: string
            email:
              type: string
              nullable: true
            cpf:
              type: string
              nullable: true
        requests:
          update:
            title: Update User Request
            type: object
            properties:
              user:
                type: object
                properties:
                  full_name:
                    type: string
                  cpf:
                    type: string
                    nullable: true
                  email:
                    type: string
                    nullable: true
                required:
                - user
        responses:
          show:
            title: Show User Response
            type: object
            properties:
              data:
                "$ref": "#/components/schemas/v1/users/_private"
            required:
            - data
servers:
- url: http://localhost:3000
