---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/auth/login":
    post:
      summary: Login user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    message: Logged in successfully.
                    token: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI5ODQ1YWVkMi1hM2MxLTQxMTYtODI4YS1mOGRhMTk1NTllZDIiLCJzdWIiOiJmNGFjZjYzYy00ODNiLTQ3NmYtOTU5Yy00Yzc3ZjNjMzgwZmMiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE3NDY2NzE5MzEsImV4cCI6MTc0Njc1ODMzMX0.ZkYRz4QIfBFAiH05zwBVtron8xsrGonG38V-9d1kNAY
                    refresh_token:
                      value: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmNGFjZjYzYy00ODNiLTQ3NmYtOTU5Yy00Yzc3ZjNjMzgwZmMiLCJqdGkiOiI5ODQ1YWVkMi1hM2MxLTQxMTYtODI4YS1mOGRhMTk1NTllZDIifQ.aNrvTYTqt2N8NP9C0dumo0kd4KWBTheb9h8icbQENqU
                      httponly: true
                      expires: '2025-05-09T02:38:51.684Z'
                      secure: false
                    user:
                      id: f4acf63c-483b-476f-959c-4c77f3c380fc
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      email: test@test
                      full_name: Timika Herzog
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/auth/requests/login"
  "/api/auth/signup":
    post:
      summary: Sign up user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    message: Signed up successfully.
                    token: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMTZiZDJkMC00YTI5LTQ1ZDUtOTIxZC00NmQyZmI1Yzg2MmYiLCJzdWIiOiI1MDdlNzcyNi0xNzJmLTRmOTctYmFjMS0wZThjOWZkMjI2OGIiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE3NDY2NzE5MzEsImV4cCI6MTc0Njc1ODMzMX0.s5xUYh19fTYm7e5gmv7az17IXu50eC2FMI8moHtb6BU
                    user:
                      id: 507e7726-172f-4f97-bac1-0e8c9fd2268b
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      email: teste@teste
                      full_name: 
                    refresh_token:
                      value: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MDdlNzcyNi0xNzJmLTRmOTctYmFjMS0wZThjOWZkMjI2OGIiLCJqdGkiOiIxMTZiZDJkMC00YTI5LTQ1ZDUtOTIxZC00NmQyZmI1Yzg2MmYifQ.cE3u3CQqiPipCg-KFNYAGyn-6VMwjz9OVSINvfYXiA0
                      httponly: true
                      expires: '2025-05-09T02:38:51.728Z'
                      secure: false
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/auth/requests/signup"
  "/api/auth/logout":
    delete:
      summary: Logout User
      tags:
      - Auth
      security:
      - bearer_auth: []
      responses:
        '200':
          description: Successful
  "/api/v1/mentor/profiles/{id}":
    get:
      summary: Show Mentor Profile
      tags:
      - Profiles
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: e80ac8fd-1437-41f6-9c90-2dc340ebd02e
                      availabilities: []
                      bio: Saepe facere minima. Assumenda qui at. Animi nihil suscipit.
                      client_profiles: []
                      expertise_areas: []
                      headline: Education Administrator
                      hourly_rate: '57.28'
                      linkedin_url: http://linkedin.com/guadalupe
                      profile_name: 
                      rating: 0.78
                      sessions: []
                      years_of_experience: 10
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      base:
                      - Couldn't find Mentor::Profile with 'id'=not_an_id
                    request_id: 14059ec8-0bfa-40a6-9470-594b9f8ca891
    put:
      summary: Update Mentor Profile
      tags:
      - Mentor Profiles
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: 3d86995f-25b8-4ba1-8d13-e02484e02749
                      availabilities: []
                      bio: Updated Bio
                      client_profiles: []
                      expertise_areas: []
                      headline: Updated Headline
                      hourly_rate: '50.0'
                      linkedin_url: https://linkedin.com/in/updated
                      profile_name: Updated Profile
                      rating: 4.5
                      sessions: []
                      years_of_experience: 5
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/mentor/profile/requests/update"
  "/api/v1/users/{id}":
    get:
      summary: Show User
      tags:
      - Users
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: dad93ee8-827d-445b-8cdb-6dd98a4503d1
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      cpf: '05271249077'
                      email: cori.weber@nikolaus-kris.test
                      full_name: Jesus Hilpert
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      base:
                      - Couldn't find User with 'id'=not_an_id
                    request_id: 7dc59e05-16aa-4845-b204-4ac7f8a2cec6
    put:
      summary: Update User
      tags:
      - Users
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: 16f5c405-3078-4c3f-9ec2-e0369246e354
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      cpf: '12496062095'
                      email: admin@acme.com
                      full_name: Dummy Name
        '422':
          description: Unprocessable entity
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      email:
                      - is invalid
                    request_id: c028304b-161f-4515-bec4-9655be4d0b4b
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      base:
                      - Couldn't find User with 'id'=not_an_id
                    request_id: d377bb94-66a5-4e88-9f09-64f1e3226841
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/users/requests/update"
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
  schemas:
    auth:
      requests:
        login:
          title: User Login Request
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                  example: t@t.com
                password:
                  type: string
                  example: '123456'
              required:
              - email
              - password
          required:
          - user
        signup:
          title: Create User Request
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                  example: test@test
                password:
                  type: string
                full_name:
                  type: string
              required:
              - email
              - password
      responses:
        login:
          title: Create User Response
          type: object
          properties:
            message:
              type: string
            token:
              type: string
            refresh_token:
              type: object
              properties:
                value:
                  type: string
                httponly:
                  type: boolean
                expires:
                  type: string
                secure:
                  type: boolean
            user:
              "$ref": "#/components/schemas/v1/users/_common"
        signup:
          title: Create User Response
          type: object
          properties:
            message:
              type: string
            token:
              type: string
            refresh_token:
              type: object
              properties:
                value:
                  type: string
                httponly:
                  type: boolean
                expires:
                  type: string
                secure:
                  type: boolean
    common:
      pagination_meta:
        title: Pagination Meta
        type: object
        properties:
          current_page:
            type: integer
          total_pages:
            type: integer
          current_page_size:
            type: integer
          total:
            type: integer
        required:
        - current_page
        - total_pages
        - current_page_size
        - total
    v1:
      mentor:
        availabilities:
          _common:
            title: Mentor Availability
            type: object
            additionalProperties: true
            properties:
              id:
                type: string
              start_time:
                type: string
                format: date-time
              end_time:
                type: string
                format: date-time
          _private:
            title: Mentor Availability Private
            type: object
            additionalProperties: true
            properties:
              id:
                type: string
              start_time:
                type: string
                format: date-time
              end_time:
                type: string
                format: date-time
        expertise_areas:
          _common:
            title: Mentor ExpertiseArea
            type: object
            additionalProperties: true
            properties:
              id:
                type: string
              name:
                type: string
        profiles:
          _common:
            title: Mentor Profile
            type: object
            additionalProperties: true
            properties:
              id:
                type: string
              bio:
                type: string
              headline:
                type: string
                nullable: true
              hourly_rate:
                type: string
                nullable: true
              linkedin_url:
                type: string
                nullable: true
              profile_name:
                type: string
                nullable: true
              rating:
                type: number
                format: float
                nullable: true
              years_of_experience:
                type: integer
                nullable: true
              expertise_areas:
                type: array
                items:
                  "$ref": "#/components/schemas/v1/mentor/expertise_areas/_common"
              availabilities:
                type: array
                items:
                  "$ref": "#/components/schemas/v1/mentor/availabilities/_common"
          _private:
            title: Mentor Profile Private
            type: object
            additionalProperties: true
            allOf:
            - "$ref": "#/components/schemas/v1/mentor/profiles/_common"
            properties:
              sessions:
                type: array
                items:
                  "$ref": "#/components/schemas/v1/mentor/session"
              client_profiles:
                type: array
                items:
                  "$ref": "#/components/schemas/v1/mentor/profiles/_common"
          requests:
            update:
              title: Update Mentor Profile Request
              type: object
              properties:
                mentor_profile:
                  type: object
                  properties:
                    bio:
                      type: string
                      nullable: true
                    headline:
                      type: string
                      nullable: true
                    hourly_rate:
                      type: string
                      nullable: true
                    linkedin_url:
                      type: string
                      nullable: true
                    profile_name:
                      type: string
                      nullable: true
                    rating:
                      type: number
                      nullable: true
                    years_of_experience:
                      type: string
                      nullable: true
                  required:
                  - mentor_profile
          responses:
            show:
              title: Show Mentor Profile Response
              type: object
              properties:
                data:
                  "$ref": "#/components/schemas/v1/mentor/profiles/_private"
              required:
              - data
            update:
              title: Update Mentor Profile Response
              type: object
              properties:
                data:
                  "$ref": "#/components/schemas/v1/mentor/profiles/_private"
              required:
              - data
      users:
        _common:
          title: User
          type: object
          additionalProperties: true
          properties:
            id:
              type: string
            full_name:
              type: string
              nullable: true
            email:
              type: string
              nullable: true
        _private:
          title: User Private
          type: object
          additionalProperties: true
          properties:
            id:
              type: string
            full_name:
              type: string
            email:
              type: string
              nullable: true
            cpf:
              type: string
              nullable: true
        requests:
          update:
            title: Update User Request
            type: object
            properties:
              user:
                type: object
                properties:
                  full_name:
                    type: string
                  cpf:
                    type: string
                    nullable: true
                  email:
                    type: string
                    nullable: true
                required:
                - user
        responses:
          show:
            title: Show User Response
            type: object
            properties:
              data:
                "$ref": "#/components/schemas/v1/users/_private"
            required:
            - data
servers:
- url: http://localhost:3000
